// Code generated by ent, DO NOT EDIT.

package system

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the system type in the database.
	Label = "system"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSystemID holds the string denoting the system_id field in the database.
	FieldSystemID = "system_id"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldApproved holds the string denoting the approved field in the database.
	FieldApproved = "approved"
	// FieldLastLogin holds the string denoting the last_login field in the database.
	FieldLastLogin = "last_login"
	// Table holds the table name of the system in the database.
	Table = "systems"
)

// Columns holds all SQL columns for system fields.
var Columns = []string{
	FieldID,
	FieldSystemID,
	FieldPublicKey,
	FieldApproved,
	FieldLastLogin,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the System queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySystemID orders the results by the system_id field.
func BySystemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemID, opts...).ToFunc()
}

// ByPublicKey orders the results by the public_key field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// ByApproved orders the results by the approved field.
func ByApproved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApproved, opts...).ToFunc()
}

// ByLastLogin orders the results by the last_login field.
func ByLastLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLogin, opts...).ToFunc()
}
